export default {
  tintColor: '#259dba',
  whiteColor: '#ffffff',
  whiteColor1: '#f8f9fa',
  blackColor: '#000000',
  blackColor1: '#212529',
  blueColor: '#259dba',
  redColor: '#FF0000',
  greenColor: '#28a745',
  loginBackground: '#ffffff',
  tabIconDefault: '#b3f2f9',
  tabIconSelected: '#ffffff',
  tabBar: '#259dba',
  activeTextTintColor: '#ffffff',
  textTintColor: '#b3f2f9',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#FF0000',
  drawerIcon: '#259dba',
  borderColor: '#E4E4E4'
};
