require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '11.0'

target 'TheGioiGiaSu' do
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])



  target 'TheGioiGiaSuTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
    #   use_flipper!({ 'Flipper' => '0.74.0' })
      post_install do |installer|
        installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
           config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
          end
         end
      end
end

target 'TheGioiGiaSu-tvOS' do
  # Pods for TheGioiGiaSu-tvOS

  target 'TheGioiGiaSu-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
